[project]
name = "proyecto4-eda-iris-amorim"
version = "0.1.0"
description = "Exploratory Data Analysis of heart disease data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "seaborn>=0.13.2",
]
